KMS_KEY_ID = "KMS KEY ID"
SECRET_KEY = "RANDOMLY GENERATED 64 CHARACTER KEY"
SQLALCHEMY_DATABASE_URI = "DATABASE URI [EXAMPLE: 'sqlite:///data.db']"
SQLALCHEMY_TRACK_MODIFICATIONS = False
BASIC_AUTH_USERNAME = "username"
BASIC_AUTH_PASSWORD = "password"
