# If you would like to use this file to test endpoints
# or to add futher requests for more testing purposes
# Please install the REST Client VsCode extension by Huachao Mao

GET http://127.0.0.1:5000/
content-type: application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "Bob Pickles",
      "userEmail": "bob@pickles.com"
  },
  "env": "test",
  "parameters": {
    "a": {
      "value": "some dumb value",
      "secret": true,
      "comment": "some dumb comment"
    },
    "b": {
      "value": "another dumb value",
      "secret": false,
      "comment": "another dumb comment"
    }
  }
}

###
# Wrong AUTH token sent to getParams
POST http://127.0.0.1:8000/getParams
content-type: application/json

{
    "authToken" : "abc123"
}

### 

# Correct AUTH token and test env
POST http://127.0.0.1:8000/getParams
content-type: application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "Bob Pickles",
      "userEmail": "bob@pickles.com"
  },
  "env": "test",
  "parameters": {
    "a": {
      "value": "some dumb value",
      "secret": true,
      "comment": "some dumb comment"
    },
    "b": {
      "value": "another dumb value",
      "secret": false,
      "comment": "another dumb comment"
    }
  }
}

###
# Correct AUTH token and prod env
POST http://127.0.0.1:8000/getParams
content-type: application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "Bob Pickles",
      "userEmail": "bob@pickles.com"
  },
  "env": "prod",
  "parameters": {
    "a": {
      "value": "some dumb value",
      "secret": true,
      "comment": "some dumb comment"
    },
    "b": {
      "value": "another dumb value",
      "secret": false,
      "comment": "another dumb comment"
    }
  }
}

###

# Correct AUTH token sent to putParams
# Basic config params
POST http://127.0.0.1:8000/putParams
content-type: application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "Bob Pickles",
      "userEmail": "bob@pickles.com"
  },
  "env": "test",
  "parameters": {
    "a": {
      "value": "some dumb value",
      "secret": true,
      "comment": "some dumb comment"
    },
    "b": {
      "value": "another dumb value",
      "secret": false,
      "comment": "another dumb comment"
    }
  }
}

###

# Correct AUTH token sent to putParams
# Secret, Delete and Missing params (param exists in yml not in json request)
POST http://127.0.0.1:8000/putParams
content-type: application/json

{
    "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
    "userInfo": {
        "userName": "Neil Clack",
        "userEmail": "c.neilclack@gmail.com"
    },
    "parameters": {
        "a": {
            "delete" : true
        },
        "b": {
            "value": "another dumb value",
            "secret": false,
            "comment": "another dumb comment"
        },
        "c": {
            "value": "This is value C",
            "secret":true,
            "comment":"This is a new, secret value. Not previously stored in .yml file."
        }
    }
}
