###
# Return ALL params stored in params table
POST http://localhost:8000/getparams HTTP/1.1
Authorization: Basic dXNlcm5hbWU=:cGFzc3dvcmQ=
content-type: Application/json

{
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  }
}

###
# Return ALL updates
POST http://localhost:8000/getupdates HTTP/1.1
Authorization: Basic dXNlcm5hbWU=:cGFzc3dvcmQ=
content-type: Application/json

{
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  }
}


###
# Create or update a single new parameter
POST http://localhost:8000/save HTTP/1.1
Authorization: Basic dXNlcm5hbWU=:cGFzc3dvcmQ=
content-type: Application/json

{
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  },
  "env": "prod",
  "parameters": [{
    "name":"testing",
    "prefix":"sectretized",
    "value":"This is a new, unencrypted value",
    "secret":true,
    "comment": "Is this updating correctly...?"
  }]
}

###
# Create or update several new parameters
POST http://localhost:8000/save HTTP/1.1
Authorization: Basic dXNlcm5hbWU=:cGFzc3dvcmQ=
content-type: Application/json

{
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  },
  "env": "prod",
  "parameters": [{
    "name": "09876543",
    "prefix": "dev-100",
    "value": "This is a copy of another parameter to create tests",
    "secret": false,
    "comment": "More Lorem ipsum"
  },
  {
    "name":"test_param",
    "prefix":"sprint101",
    "value":"I don't know, I'm just going to include some sort of data string here....",
    "secret": true,
    "comment": "Lorem ipsum"
  }]
}

###
POST http://localhost:8000/store HTTP/1.1
Authorization: Basic dXNlcm5hbWU=:cGFzc3dvcmQ=
content-type: application/json

{
  "env":"prod",
  "prefix":"sprint101"
}

###
GET http://localhost:5000/test HTTP/1.1