###
# Return ALL params stored in params table
POST http://localhost:5000/getparams HTTP/1.1
content-type: Application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  }
}

###
# Return ALL updates
POST http://localhost:5000/getupdates HTTP/1.1
content-type: Application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  }
}


###
# Create a single new parameter
POST http://localhost:5000/save HTTP/1.1
content-type: Application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  },
  "parameters": [{
    "name": "app2",
    "value": "Some other dumbass value here",
    "secret": false
  }]
}

###
# Create several new parameters
POST http://localhost:5000/save HTTP/1.1
content-type: Application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  },
  "parameters": [{
    "name": "app69",
    "value": "I dunno, something has to go here...",
    "secret": false,
    "comment": "I nearly forgot about comments commpletely!"
  },
  {
    "name":"app76",
    "value":"Fallout",
    "secret":true,
    "comment": "That would have ruined the whole app!"
  }]
}

###
POST http://localhost:5000/post HTTP/1.1
content-type: Application/json

{
  "authToken": "FXbWZBmGstqCJP8D7P3kzguthu479dFv",
  "userInfo": {
    "userName": "nclack",
    "userEmail": "testing@gmail.com"
  }
}
