"""empty message

Revision ID: 71b3ab090b28
Revises: d7286ec5a855
Create Date: 2021-09-11 13:50:39.654833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b3ab090b28'
down_revision = 'd7286ec5a855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('useremail', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'useremail')
    # ### end Alembic commands ###
