"""empty message

Revision ID: d249f1e13182
Revises: 
Create Date: 2021-09-12 08:47:23.745053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd249f1e13182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=False),
    sa.Column('secret', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('useremail', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('secret', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updates')
    op.drop_table('params')
    # ### end Alembic commands ###
